name: Feature Request
description: Request a new feature to be added to Keycloak
labels: ["feature", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature at a high-level
    validations:
      required: true

  - type: textarea
    id: value_proposition
    attributes:
      label: Value Proposition
      description: Describe what value the feature brings
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: Describe what capabilities the feature should provide
    validations:
      required: true

  - type: textarea
    id: non_goals
    attributes:
      label: Non-Goals
      description: Describe capabilities the feature should not provide, or is out of scope
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Design ideas? Implementation ideas? Anything that will give us more context about the feature you are proposing!
    validations:
      required: false