< {%
    // Set mock IP for realm test here
    const mockIp = '127.0.0.1';
    client.global.set('mockIp', mockIp);
%}

## Set IP {{mockIp}} for realm test
GET {{baseUrl}}/admin/realms/test
Authorization: Bearer {{$auth.token("local-kc")}}
Accept: application/json

> {%
    const realm = response.body;
    realm.attributes['geoaware-mock-ip'] = client.global.get('mockIp');
    client.global.set('realmResponse', JSON.stringify(realm));
%}

###
PUT {{baseUrl}}/admin/realms/test
Authorization: Bearer {{$auth.token("local-kc")}}
Content-Type: application/json

{{realmResponse}}

> {%
    client.assert(response.status === 204, 'Expected HTTP 204, but received ' + response.status);
%}